# Turns the committed cvar documentation into a C++ source file for odalaunch.
#
#   cmake -D CLIENT_JSON=<path> -D SERVER_JSON=<path> -D OUTPUT=<path>
#         -P embed_cvardoc.cmake
#
# The documents are emitted as byte arrays.

cmake_minimum_required(VERSION 3.19)

foreach(_required CLIENT_JSON SERVER_JSON OUTPUT)
  if(NOT DEFINED ${_required})
    message(FATAL_ERROR "embed_cvardoc: ${_required} must be set")
  endif()
endforeach()

# Renders one document as a C array definition plus its length.
function(cvardoc_emit_array out_var symbol path)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "embed_cvardoc: no such file: ${path}")
  endif()

	# Read file as hex, get length in bytes
  file(READ "${path}" _hex HEX)

  string(LENGTH "${_hex}" _hexlen)
  math(EXPR _bytelen "${_hexlen} / 2")
  if(_bytelen EQUAL 0)
    message(FATAL_ERROR "embed_cvardoc: ${path} is empty")
  endif()

  # Break up one big hex string into smaller byte chars
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")

  # Break the lines up so the file is not one enormous line.
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
    "\\1\n\t" _bytes "${_bytes}")

  set(${out_var}
    "extern const char ${symbol}[] = {\n\t${_bytes}\n};\nextern const size_t ${symbol}_LEN = ${_bytelen};\n\n"
    PARENT_SCOPE)
endfunction()

cvardoc_emit_array(CLIENT_ARRAY ODAMEX_CVARDOC_JSON "${CLIENT_JSON}")
cvardoc_emit_array(SERVER_ARRAY ODASRV_CVARDOC_JSON "${SERVER_JSON}")

get_filename_component(CLIENT_NAME "${CLIENT_JSON}" NAME)
get_filename_component(SERVER_NAME "${SERVER_JSON}" NAME)

set(CONTENTS "// Generated by tools/cvardoc/embed_cvardoc.cmake - do not edit.\n")
string(APPEND CONTENTS "//\n")
string(APPEND CONTENTS "// Source documents: ${CLIENT_NAME}, ${SERVER_NAME}\n")
string(APPEND CONTENTS "\n#include <cstddef>\n\n")
string(APPEND CONTENTS "${CLIENT_ARRAY}")
string(APPEND CONTENTS "${SERVER_ARRAY}")

# Only rewrite when the contents change, so odalaunch does not relink for a
# regenerated but identical source.
set(EXISTING "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" EXISTING)
endif()

if(NOT EXISTING STREQUAL CONTENTS)
  file(WRITE "${OUTPUT}" "${CONTENTS}")
endif()
