find_package(ZLIB REQUIRED)
find_package(PNG REQUIRED)
find_package(CURL REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(FLTK CONFIG REQUIRED)
find_package(jsoncpp CONFIG REQUIRED)
find_package(minilzo CONFIG REQUIRED)
find_package(miniupnpc CONFIG REQUIRED)
find_package(PortMidi CONFIG REQUIRED)
find_package(protobuf CONFIG REQUIRED)
find_package(SDL2 CONFIG REQUIRED)
find_package(SDL2_mixer CONFIG REQUIRED)
find_package(wxWidgets CONFIG REQUIRED)
