name: Post clang-tidy comments

on:
  workflow_run:
    workflows: ["clang-tidy"]
    types:
      - completed

jobs:
  clang-tidy-comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.23.1
        with:
          num_comments_as_exitcode: false
          lgtm_comment_body: ""
